name: supertokens_flutter
description: SuperTokens SDK for Flutter apps
version: 0.5.0
homepage: https://supertokens.com/
repository: https://github.com/supertokens/supertokens-flutter
issue_tracker: https://github.com/supertokens/supertokens-flutter/issues
documentation: https://supertokens.com/docs
platforms:
  android:
  ios:

environment:
  sdk: ">=2.12.0 <3.9.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: "<2.0.0"
  shared_preferences: ">=2.0.0 <3.0.0"
  mutex: ^3.1.0
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.4
  dio_http_formatter: ^3.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
